viewer:
  eye: !!python/tuple
  - 7.5
  - 7.5
  - 7.5
  lookat: !!python/tuple
  - 0.0
  - 0.0
  - 0.0
  cam_prim_path: /OmniverseKit_Persp
  resolution: !!python/tuple
  - 1280
  - 720
  origin_type: world
  env_index: 0
  asset_name: null
  body_name: null
sim:
  physics_prim_path: /physicsScene
  device: cuda:0
  dt: 0.008333333333333333
  render_interval: 2
  gravity: !!python/tuple
  - 0.0
  - 0.0
  - -9.81
  enable_scene_query_support: false
  use_fabric: true
  physx:
    solver_type: 1
    min_position_iteration_count: 1
    max_position_iteration_count: 255
    min_velocity_iteration_count: 0
    max_velocity_iteration_count: 255
    enable_ccd: false
    enable_stabilization: false
    enable_enhanced_determinism: false
    bounce_threshold_velocity: 0.5
    friction_offset_threshold: 0.04
    friction_correlation_distance: 0.025
    gpu_max_rigid_contact_count: 8388608
    gpu_max_rigid_patch_count: 163840
    gpu_found_lost_pairs_capacity: 2097152
    gpu_found_lost_aggregate_pairs_capacity: 33554432
    gpu_total_aggregate_pairs_capacity: 2097152
    gpu_collision_stack_size: 67108864
    gpu_heap_capacity: 67108864
    gpu_temp_buffer_capacity: 16777216
    gpu_max_num_partitions: 8
    gpu_max_soft_body_contacts: 1048576
    gpu_max_particle_contacts: 1048576
    solve_articulation_contact_last: false
  physics_material:
    func: isaaclab.sim.spawners.materials.physics_materials:spawn_rigid_body_material
    static_friction: 1.0
    dynamic_friction: 1.0
    restitution: 0.0
    friction_combine_mode: multiply
    restitution_combine_mode: multiply
    compliant_contact_stiffness: 0.0
    compliant_contact_damping: 0.0
  render:
    enable_translucency: null
    enable_reflections: null
    enable_global_illumination: null
    antialiasing_mode: null
    enable_dlssg: null
    enable_dl_denoiser: null
    dlss_mode: null
    enable_direct_lighting: null
    samples_per_pixel: null
    enable_shadows: null
    enable_ambient_occlusion: null
    dome_light_upper_lower_strategy: null
    carb_settings: null
    rendering_mode: null
  create_stage_in_memory: false
  logging_level: WARNING
  save_logs_to_file: true
ui_window_class_type: uav_payload_lab.tasks.direct.uav_payload_lab.uav_payload_lab_env_cfg:UavPayloadLabEnvWindow
seed: 42
decimation: 2
is_finite_horizon: false
episode_length_s: 35.0
scene:
  num_envs: 4096
  env_spacing: 6
  lazy_sensor_update: true
  replicate_physics: true
  filter_collisions: true
  clone_in_fabric: true
events: null
observation_space: 17
num_observations: null
state_space: 0
num_states: null
observation_noise_model: null
action_space: 4
num_actions: null
action_noise_model: null
rerender_on_reset: false
num_rerenders_on_reset: 0
wait_for_textures: true
xr: null
log_dir: /home/shenji/uav_payload_lab/uav_payload_lab/logs/rsl_rl/uav_payload_antisway/2025-12-05_03-04-56
terrain:
  class_type: isaaclab.terrains.terrain_importer:TerrainImporter
  collision_group: -1
  prim_path: /World/ground
  num_envs: 4096
  terrain_type: plane
  terrain_generator: null
  usd_path: null
  env_spacing: 6
  use_terrain_origins: true
  visual_material:
    func: isaaclab.sim.spawners.materials.visual_materials:spawn_preview_surface
    diffuse_color: !!python/tuple
    - 0.0
    - 0.0
    - 0.0
    emissive_color: !!python/tuple
    - 0.0
    - 0.0
    - 0.0
    roughness: 0.5
    metallic: 0.0
    opacity: 1.0
  physics_material:
    func: isaaclab.sim.spawners.materials.physics_materials:spawn_rigid_body_material
    static_friction: 1.0
    dynamic_friction: 1.0
    restitution: 0.0
    friction_combine_mode: multiply
    restitution_combine_mode: multiply
    compliant_contact_stiffness: 0.0
    compliant_contact_damping: 0.0
  max_init_terrain_level: null
  debug_vis: false
robot:
  class_type: isaaclab.assets.articulation.articulation:Articulation
  prim_path: /World/envs/env_.*/Robot
  spawn:
    func: isaaclab.sim.spawners.from_files.from_files:spawn_from_usd
    visible: true
    semantic_tags: null
    copy_from_source: false
    mass_props: null
    deformable_props: null
    rigid_props:
      rigid_body_enabled: null
      kinematic_enabled: null
      disable_gravity: false
      linear_damping: null
      angular_damping: null
      max_linear_velocity: null
      max_angular_velocity: null
      max_depenetration_velocity: 10.0
      max_contact_impulse: null
      enable_gyroscopic_forces: true
      retain_accelerations: null
      solver_position_iteration_count: null
      solver_velocity_iteration_count: null
      sleep_threshold: null
      stabilization_threshold: null
    collision_props: null
    activate_contact_sensors: false
    scale: null
    articulation_props:
      articulation_enabled: null
      enabled_self_collisions: false
      solver_position_iteration_count: 4
      solver_velocity_iteration_count: 0
      sleep_threshold: 0.005
      stabilization_threshold: 0.001
      fix_root_link: null
    fixed_tendons_props: null
    spatial_tendons_props: null
    joint_drive_props: null
    visual_material_path: material
    visual_material: null
    usd_path: /home/shenji/uav_payload_lab/uav_payload_lab/source/uav_payload_lab/uav_payload_lab/tasks/direct/uav_payload_lab/iris_payload.usd
    variants: null
  init_state:
    pos: !!python/tuple
    - 0.0
    - 0.0
    - 1.2
    rot: !!python/tuple
    - 1.0
    - 0.0
    - 0.0
    - 0.0
    lin_vel: !!python/tuple
    - 0.0
    - 0.0
    - 0.0
    ang_vel: !!python/tuple
    - 0.0
    - 0.0
    - 0.0
    joint_pos:
      .*: 0.0
    joint_vel:
      .*: 0.0
  collision_group: 0
  debug_vis: false
  articulation_root_prim_path: null
  soft_joint_pos_limit_factor: 1.0
  actuators:
    dummy:
      class_type: isaaclab.actuators.actuator_pd:ImplicitActuator
      joint_names_expr:
      - .*
      effort_limit: null
      velocity_limit: null
      effort_limit_sim: null
      velocity_limit_sim: null
      stiffness: 0.0
      damping: 0.0
      armature: null
      friction: null
      dynamic_friction: null
      viscous_friction: null
  actuator_value_resolution_debug_print: false
debug_vis: true
thrust_to_weight: 1.9
moment_scale: 0.4
rope_length: 0.8
sigma_pos: 0.2
sigma_tilt_deg: 40.0
sigma_swing_deg_s: 45.0
pos_weight: 0.3
tilt_weight: 0.05
time_penalty: 0.01
death_penalty: 20
start_pos_w: !!python/tuple
- 0.5
- 1.0
- 1.2
goal_pos_w: !!python/tuple
- -0.5
- 0.0
- 1.2
